### ISSUE TITLE
Cosmetic suggestion for plots

### ISSUE THREAD

**Issue by bjoernholzhauer** [AlliedToasters/dfencoder#2]
It was awesome and great, how fast I got an example going, but I was initially a bit confused by the progress plots. This was due to the time it took until the loss got below 1.0 and showed up (before that I had an empty plot area). Since the axes are getting updated anyway, it might be a good idea to initially leave the y-axis unrestricted and only restrict it to (0,1) (or some other range) once all the relevant losses are below 1.0. For my example, I think that the baseline validation loss was actually outside the plot area, I wonder whether that should always be on the plot?

**Comment by AlliedToasters** [comment]
@bjoernholzhauer , thanks for the rec. As of version `0.0.36`, the y-scale for the loss plots is dynamically sized based on all the data being plotted. This should help solve this issue generally. Sorry for the very late reply!
