### ISSUE TITLE
Network architecture

### ISSUE THREAD

**Issue by nsidn98** [AlliedToasters/dfencoder#8]
Would it be possible to have a look at the network architecture diagram where we could examine what is happening with each type of input variable(numeric, categorical, binary)? 

Thanks!

**Comment by AlliedToasters** [comment]
This is a good idea! I'll see if I can create some sort of HLD for this.

**Comment by AlliedToasters** [comment]
Ok, I added [a HLD](https://github.com/AlliedToasters/dfencoder/blob/master/demo_data/input_handling_hld.png) and it's now embedded in the [README.md](README.md) doc.
