### ISSUE TITLE
show_embeddings() function is missing from 'IpynbLogger'

### ISSUE THREAD

**Issue by shuowenwei** [AlliedToasters/dfencoder#9]
Awecome repo first of all! Thank you! 

When I ran the demo notebook I have the follow errors, I think show_embeddings() function is missing from 'IpynbLogger' class: 

AttributeError: 'IpynbLogger' object has no attribute 'show_embeddings'

**Comment by shuowenwei** [comment]
@AlliedToasters  this is what I changed in autoencoder.py line 615: 


                    if self.project_embeddings **and isinstance(self.logger, TensorboardXLogger):**
                        self.logger.show_embeddings(self.categorical_fts)

**Comment by zaky9** [comment]
Hi after I updated with your correction, I received this error (below). Any solution?


TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by AlliedToasters** [comment]
Hey all, the original issue has been fixed with release of `v0.0.37`. Please give it a go!
